language: c
sudo: false
script:
  - git fetch --depth=1
  - git fetch --unshallow
  - git fetch origin '+refs/heads/master:refs/heads/master'
  - git fetch origin '+refs/heads/develop:refs/heads/develop'
  - git fetch --tags
  - git checkout -qf $TRAVIS_BRANCH
  - git submodule init
  - git submodule update
  - cd lib/other/nanopb/generator/proto && make && cd ../../../../..
  - cd lib/libopencm3 && make && cd ../..
  - python /usr/bin/scons proto
  - python /usr/bin/scons

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-6-2017-q2-update

before_install:
  - export PATH=$HOME/.local/bin:$HOME/protobuf/bin:$PATH
  - source ~/virtualenv/python2.7/bin/activate

install:
  - pip install gitpython
  - pip install pyyaml
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
    && curl -LO 'https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip'
    && unzip protoc-3.4.0-linux-x86_64.zip
    && popd
  - curl -L 'https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-python-3.4.0.tar.gz' | tar xzf -
    && pushd protobuf-3.4.0/python
    && python setup.py build && python setup.py install
    && popd
  - export GCC_DIR=$HOME/gcc-arm-none-eabi-6-2017-q2-update
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-gcc ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
  - export PATH=$PATH:$GCC_DIR/bin

deploy:
  provider: releases
  api_key:
    secure: FDoxUZ6d1e0lUA7NrtuvmtK+QU4VN5fGtyB2uUKW8/yV6petaGLMfTKgO0F0y7fEAF2VAxmYM7C3R1W+zl7jXhPz7YBO0QOJPatk/yQX7Mn9NHbCNPROW8KpSzlu+Ma6pFE21MZ+yvk6ugKa5gHZs+9wOEmbdqpk5Szpl0vA/b+EoDYGAdEwTfp/1e973XQX4pHcgd8sLftruDfuNfaEfVbgdRsIHyp7Rqxrgh2aksd0GQEuqIFq8YzztvX8Ir6BU8YJnZHvYvG4cL64LlMuLkMj2GDdUPMZpd7DLLkIliaz9irgP7m5dIvA6i8071ks1lpTRFE29klw5VBn/cLNcRTqSNCIXr1IPiP5vNJmscwk4tbOcjXPl29cz8Eue/r7XSciIqFK4xuiJXfv1oeFFxvpMKpm+tEdo5BQqiW9FL+6LZXIZdOjNgrs7cbOrH/6EHbQlGOE+v3ta4rlV6aAFywYGXfN/99E2HFpG02AYdMZvrRwPdpCSLUTwiAo1g3Fsig5H2v5qwFTcURtV4FxcK2ucEXolVGHqQSBnbqCRITyUKpf6lhW+JiV5tCaR9iWUfR6bfGZ+JrSoJYYdDmabOiHw8grPu9m8Afs5YkCuDglDm8Rp7hMtZ5d51Vqq2v+Op+Y+ZiQRBUs+muKZT94j0Zvu9kFAn6HbaVawvxcc2M=
  file_glob: true
  file:
    bin/*.fw
    bin/*.elf
  on:
    tags: true
